import { z } from "zod";

export const apiErrorCodeSchema = z.enum([
  "internal_error",
  "validation_error",
  "not_found",
  "unauthorized",
  "forbidden",
  "conflict",
  "rate_limited",
  "insufficient_allowance",
  "insufficient_usage",
  "invalid_topup_amount",
  "no_active_subscription",
  "reservation_not_found",
  "reservation_already_settled",
  "reservation_already_released",
  "reservation_conflict",
  "financial_operation_failed",
  "ai_disabled",
  "ai_request_in_progress",
  "ai_request_cost_limit",
  "ai_provider_balance_unavailable",
  "ai_reconciliation_required",
  "unknown_model",
  "inactive_model",
  "model_unavailable",
  "message_too_large",
  "origin_forbidden",
  "concurrency_limited",
  "email_not_verified",
  "invalid_credentials",
  "invalid_otp",
  "otp_expired",
  "otp_too_many_attempts",
  "otp_resend_too_soon",
  "invalid_reset_token",
  "reset_token_expired",
  "session_not_found",
  "notification_temporarily_unavailable",
  "notification_not_found",
  "payment_temporarily_unavailable",
  "payment_not_found",
  "payment_already_processed",
  "payment_amount_invalid",
  "payment_reconciliation_required",
  "payment_provider_unavailable",
  "payment_rate_limited",
  "subscription_already_active",
  "invalid_timezone",
  "timezone_required",
  "workspace_payload_too_large",
  "workspace_reorder_invalid",
  "workspace_list_full",
  "workspace_status_invalid",
  "operator_disabled",
  "operator_run_in_progress",
  "operator_confirmation_required",
  "operator_confirmation_invalid",
  "operator_clarification_required",
  "operator_plan_invalid",
  "operator_tool_denied",
  "direct_chats_disabled",
  "direct_chat_device_revoked",
  "direct_chat_recipient_device_missing",
  "direct_chat_context_denied",
  "projects_disabled",
  "project_plan_locked",
  "project_entitlement_denied",
  "project_owned_limit",
  "project_member_limit",
  "project_invite_invalid",
  "project_invite_email_mismatch",
  "project_role_forbidden",
]);
export type ApiErrorCode = z.infer<typeof apiErrorCodeSchema>;

export const apiErrorResponseSchema = z.object({
  error: z.object({
    code: apiErrorCodeSchema,
    message: z.string(),
    requestId: z.string().optional(),
  }),
});
export type ApiErrorResponse = z.infer<typeof apiErrorResponseSchema>;
